name: sync_chrome_ext
on: push
jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - run: npm install
      - run: npm test
